### ISSUE TITLE
Errors upload firmware via wifi

### ISSUE THREAD

**Issue by mmosca** [FormationFlight/FormationFlight#36]
**Describe the bug**
Using VSCode to Upload firmware to Elrs RP2 receiver over wifi only works if you do a clean build, otherwise you get firmware too big errors.

**To Reproduce**
1. Go to PlatformIO and Upload Firmware via wifi, from a clean build
2. Upload process will succed and build log will report some reducion in size due to compression:
```Compression reduced firmware size by 73% (was 432752 bytes, now 317072 bytes)```
3. Wait for receiver to reboot and reconnect to wifi.
4. Try to Upload again, without cleaning first.
5. Log will report no reduction in size from compression and upload will fail
```Compression reduced firmware size by 100% (was 432752 bytes, now 432752 bytes)```

This was observed on the a recent merge on master with my GNSS_INJECT related changes.
Ideally, upload should work without a prior clean.

**Comment by MUSTARDTIGERFPV** [comment]
This should be fixed by the latest OTA reworks.
