### ISSUE TITLE
Arrow showing the flight direction of other aircraft is not correct

### ISSUE THREAD

**Issue by FinalFrag** [FormationFlight/FormationFlight#49]
**Describe the bug**
Arrow showing the flight direction of other aircraft is not correct. See https://youtu.be/YaEsgPmNAfI

**Expected behavior**
At the start of the clip the arrow should indicate away from me and turn towards the left.

**Observed behavior**
The arrow is pointing towards me.

**Screenshots / Logs**

**FC Firmware / Version**
iNav 6.1.1

**Comment by pitts-mo** [comment]
Was this using a new build from master in the last couple days? I believe
recently merged PR #47 should resolve this.
-p

https://github.com/FormationFlight/FormationFlight/pull/47
